-- Update categories with descriptions
UPDATE categories SET description = 'Heritage and iconic car stories' WHERE slug = 'classics';
UPDATE categories SET description = 'Investment insights with market values and auction data' WHERE slug = 'collector';

-- Add new categories
INSERT INTO `categories` (`name`, `slug`, `description`) VALUES
                                                             ('Reviews', 'reviews', 'Expert evaluations with rating systems'),
                                                             ('Trends', 'trends', 'Market analysis and industry intelligence');

-- Add more sample articles distributed across categories
INSERT INTO `articles` (`title`, `slug`, `content`, `author_id`, `category_id`, `published_at`) VALUES
-- Classics Category (5 articles)
('The Timeless Appeal of the Porsche 911', 'porsche-911-timeless', 'Since its debut in 1963, the Porsche 911 has remained virtually unchanged in its basic design philosophy. This rear-engine sports car has evolved through generations while maintaining its distinctive silhouette and character. From the early 2.0-liter flat-six to today''s turbocharged variants, the 911 represents automotive evolution at its finest.', 1, 1, '2025-07-15 09:00:00'),
('Aston Martin DB5: Bond''s Favorite Ride', 'aston-martin-db5-bond', 'The Aston Martin DB5 gained worldwide fame as James Bond''s car of choice in Goldfinger and Thunderball. Beyond its cinematic legacy, the DB5 represents British automotive excellence with its elegant design by Carrozzeria Touring and powerful 4.0-liter straight-six engine. It remains one of the most desirable classic cars ever made.', 1, 1, '2025-07-18 14:30:00'),
('Mercedes-Benz 300SL Gullwing: Engineering Marvel', 'mercedes-300sl-gullwing', 'The Mercedes-Benz 300SL Gullwing doors weren''t just for show – they were a necessity due to the car''s innovative space frame chassis. This 1954 masterpiece was the world''s fastest production car, capable of 160 mph thanks to its fuel-injected 3.0-liter inline-six engine. Today, it''s considered the holy grail of Mercedes collectibles.', 1, 1, '2025-07-19 11:15:00'),
('Lamborghini Miura: The First Supercar', 'lamborghini-miura-first-supercar', 'When Lamborghini unveiled the Miura in 1966, it redefined what a sports car could be. With its mid-mounted V12 engine and stunning Bertone bodywork, the Miura established the template for every supercar that followed. Its combination of raw power and Italian artistry created a legend that still influences automotive design today.', 1, 1, '2025-07-20 16:45:00'),
('Shelby Cobra: American Racing Legend', 'shelby-cobra-racing-legend', 'Carroll Shelby''s vision of combining British chassis engineering with American V8 power created one of the most feared racing cars of the 1960s. The AC Cobra dominated both road and track, with its lightweight construction and massive Ford engines creating a power-to-weight ratio that few cars could match.', 1, 1, '2025-07-21 13:20:00'),

-- Collector Category (6 articles)
('Investment Grade: Ferrari 250 Series Market Analysis', 'ferrari-250-investment-analysis', 'The Ferrari 250 series continues to dominate auction houses worldwide. Recent sales data shows the 250 GTO leading at $70+ million, while the 250 GT California Spider commands $15-20 million. Market experts predict continued growth due to limited production numbers and increasing global wealth among collectors.', 1, 2, '2025-07-16 10:30:00'),
('Porsche 911 Turbo: Modern Classic Investment', 'porsche-911-turbo-investment', 'Early Porsche 911 Turbos (1975-1989) have seen remarkable appreciation, with pristine examples now commanding $200,000+. The combination of iconic "whale tail" spoiler, legendary reliability, and limited production makes these cars increasingly attractive to collectors seeking both performance and investment potential.', 1, 2, '2025-07-17 15:00:00'),
('McLaren F1: The $20 Million Hypercar', 'mclaren-f1-20-million', 'Once the world''s fastest production car, the McLaren F1 has become the ultimate collector''s prize. With only 106 units produced and recent auction results exceeding $20 million, the F1 represents the pinnacle of 1990s automotive engineering and investment potential.', 1, 2, '2025-07-22 09:45:00'),
('Classic Muscle Car Market Trends 2025', 'muscle-car-market-trends-2025', 'American muscle cars are experiencing a renaissance among collectors. Plymouth ''Cuda, Dodge Challenger R/T, and Chevrolet Chevelle SS models are seeing 15-20% annual appreciation. Barn finds and restoration projects are becoming increasingly valuable as original examples become scarce.', 1, 2, '2025-07-23 12:00:00'),
('European Classics: Hidden Investment Gems', 'european-classics-hidden-gems', 'While Ferrari and Porsche dominate headlines, savvy collectors are discovering value in Alfa Romeo Giulia Quadrifoglio, BMW 2002 Turbo, and Mercedes-Benz 190E 2.5-16 Evolution. These models offer significant upside potential at current market prices.', 1, 2, '2025-07-24 14:15:00'),
('Auction House Analysis: Barrett-Jackson vs RM Sotheby''s', 'auction-house-analysis-2025', 'Comparing major auction houses reveals different market segments. Barrett-Jackson excels in American classics and muscle cars, while RM Sotheby''s dominates European exotics and racing provenance vehicles. Understanding these differences is crucial for serious collectors.', 1, 2, '2025-07-25 16:30:00'),

-- Reviews Category (6 articles)
('Driving Review: 1967 Shelby GT500', 'shelby-gt500-1967-review', 'Behind the wheel of a pristine 1967 Shelby GT500, the 428 Police Interceptor V8 delivers brutal acceleration that pins you to the seat. The heavy clutch and unassisted steering remind you this is a machine from a different era. Rating: 9/10 for authenticity, 7/10 for daily usability.', 1, 3, '2025-07-26 11:00:00'),
('Track Test: Ferrari 288 GTO Performance', 'ferrari-288-gto-track-test', 'On the track, the Ferrari 288 GTO reveals its racing DNA. The twin-turbo V8 provides explosive power delivery, while the advanced aerodynamics keep it planted at speed. This is Ferrari''s Group B homologation special at its finest. Rating: 10/10 for performance, 8/10 for comfort.', 1, 3, '2025-07-27 13:45:00'),
('Restoration Review: Jaguar E-Type Series 1', 'jaguar-e-type-restoration-review', 'This concours-level E-Type restoration showcases what happens when no expense is spared. Every component has been rebuilt to better-than-new standards. The result is a car that drives exactly as Jaguar intended in 1961. Rating: 9/10 for craftsmanship, 10/10 for authenticity.', 1, 3, '2025-07-28 10:20:00'),
('Modern Classic Review: BMW M3 E30', 'bmw-m3-e30-review', 'The original M3 remains the benchmark for sports sedans. Its naturally aspirated S14 engine loves to rev, while the precise handling makes every corner a joy. This is BMW M Division at its purest. Rating: 9/10 for driving dynamics, 8/10 for practicality.', 1, 3, '2025-07-29 15:30:00'),
('Comparison Test: Countach vs Testarossa', 'countach-vs-testarossa-comparison', 'Two 1980s icons go head-to-head. The Lamborghini Countach wins on drama and presence, while the Ferrari Testarossa offers superior refinement and usability. Both represent the excess of their era perfectly. Countach: 8/10, Testarossa: 9/10.', 1, 3, '2025-07-30 12:15:00'),
('Buyer''s Guide: Porsche 930 Turbo', 'porsche-930-turbo-buyers-guide', 'The original 911 Turbo demands respect and knowledge. Look for rust in rear wheel wells, check for boost leaks, and ensure the legendary turbo lag hasn''t been modified away. A good 930 is an incredible experience. Rating: 9/10 for excitement, 6/10 for beginners.', 1, 3, '2025-07-31 14:00:00'),

-- Trends Category (5 articles)
('Electric Classics: The Future of Vintage Cars', 'electric-classics-future-trend', 'Companies like Lunaz and Electric GT are converting classic cars to electric power. While purists debate authenticity, these conversions offer zero-emission driving with classic style. The trend is gaining momentum among environmentally conscious collectors.', 1, 4, '2025-08-01 09:30:00'),
('Youngtimer Market: 1990s Cars Gaining Value', 'youngtimer-market-1990s-trend', 'Cars from the 1990s are entering classic status. Toyota Supra, Nissan Skyline GT-R, and Honda NSX are leading the charge. These technologically advanced machines represent the last analog supercars before electronic intervention became standard.', 1, 4, '2025-08-02 11:45:00'),
('Digital Collecting: NFTs Meet Classic Cars', 'digital-collecting-nfts-classics', 'The intersection of blockchain technology and classic cars is creating new collecting opportunities. Digital ownership certificates, virtual car shows, and NFT-backed fractional ownership are changing how we think about car collecting in the digital age.', 1, 4, '2025-08-03 13:00:00'),
('Sustainable Restoration: Eco-Friendly Practices', 'sustainable-restoration-eco-friendly', 'The classic car industry is embracing sustainable practices. Water-based paints, recycled materials, and renewable energy in restoration shops are reducing environmental impact while maintaining quality standards. This trend appeals to younger collectors.', 1, 4, '2025-08-04 15:15:00'),
('Global Market Shift: Asian Collectors Rising', 'global-market-asian-collectors', 'Asian collectors are increasingly influential in the classic car market. Japanese domestic market cars are gaining international recognition, while Chinese collectors are driving demand for European exotics. This shift is reshaping global auction dynamics.', 1, 4, '2025-08-05 10:00:00');
