services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=grip_and_grin_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=3306
      - APP_DEBUG=true
      - APP_ENV=development

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grip_and_grin_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
    depends_on:
      - mysql

volumes:
  mysql_data:
