services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grip_and_grin_app
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: grip_and_grin_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: grip_and_grin_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: grip_and_grin_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
